### ISSUE TITLE
Cannot add Vector Tile Layer

### ISSUE THREAD

**Issue by doublebyte1** [frontiersi/leaflet-ogc-layers#1]
Tried to act a vector tile layer, available on [this](http://ec2-3-65-14-187.eu-central-1.compute.amazonaws.com:5000)  url, without success.

[This](https://github.com/PascalLike/leaflet-ogc-layers/blob/master/index.html) is the relevant code:

![leaflet_screenshot](https://user-images.githubusercontent.com/1038897/120192376-676c7a00-c21b-11eb-817b-0cbc66e1bb92.png)

Maybe the `ogcTilesLayer` class only applies to raster tiles?

**Comment by rowanwins** [comment]
Yeah this is currently designed for raster tiles. I could certainly look at extending to support vector tiles as well.

**Comment by doublebyte1** [comment]
Thank you for the clarification! I will close the issue then
